# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Allows publishing package to https://npm.pkg.github.com
    permissions:
      contents: read
      packages: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4

      - run: npm ci

      - name: Run tests (on Linux)
        run: xvfb-run -a npm test
        if: runner.os == 'Linux'
      - name: Run tests (not on Linux)
        run: npm test
        if: runner.os != 'Linux'

      - name: Publish extension
        run: npx vsce publish
        env:
          VSCE_PAT: ${{ secrets.AZURE_DEVOPS_TOKEN }}